"""Seed script for populating the candidates table with realistic physician data.

Run with: python -m scripts.seed_candidates
Requires SUPABASE_URL and SUPABASE_KEY in environment or .env file.
"""

import sys
import os

# Add parent directory to path for imports
sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

import httpx
from app.config import get_settings


CANDIDATES = [
    {
        "id": "c001",
        "name": "Dr. Sarah Chen",
        "specialty": "Cardiology",
        "years_experience": 8,
        "location": "Boston, MA",
        "board_certified": True,
        "licenses": ["MA", "NY", "CT"],
        "education": "Harvard Medical School; Residency at Massachusetts General Hospital; Fellowship at Brigham and Women's Hospital",
        "skills": [
            "Interventional Cardiology",
            "Cardiac Catheterization",
            "Echocardiography",
            "Transesophageal Echo",
            "Nuclear Cardiology",
            "Heart Failure Management",
        ],
        "availability": "30 days",
        "preferred_employment": ["full-time"],
    },
    {
        "id": "c002",
        "name": "Dr. James Wilson",
        "specialty": "Internal Medicine",
        "years_experience": 12,
        "location": "Chicago, IL",
        "board_certified": True,
        "licenses": ["IL", "IN", "WI"],
        "education": "Northwestern University Feinberg School of Medicine; Residency at University of Chicago Medical Center",
        "skills": [
            "Hospital Medicine",
            "Geriatric Care",
            "Diabetes Management",
            "Hypertension",
            "Preventive Medicine",
            "Clinical Teaching",
        ],
        "availability": "Immediately",
        "preferred_employment": ["full-time", "part-time"],
    },
    {
        "id": "c003",
        "name": "Dr. Maria Rodriguez",
        "specialty": "Pediatrics",
        "years_experience": 5,
        "location": "Miami, FL",
        "board_certified": True,
        "licenses": ["FL", "GA"],
        "education": "University of Miami Miller School of Medicine; Residency at Nicklaus Children's Hospital",
        "skills": [
            "Neonatal Care",
            "Developmental Pediatrics",
            "Pediatric Asthma",
            "Vaccination Programs",
            "Adolescent Medicine",
        ],
        "availability": "60 days",
        "preferred_employment": ["full-time"],
    },
    {
        "id": "c004",
        "name": "Dr. Robert Thompson",
        "specialty": "Emergency Medicine",
        "years_experience": 10,
        "location": "Denver, CO",
        "board_certified": True,
        "licenses": ["CO", "UT", "WY", "NM"],
        "education": "University of Colorado School of Medicine; Residency at Denver Health",
        "skills": [
            "Trauma Management",
            "Critical Care",
            "Emergency Ultrasound",
            "Toxicology",
            "Disaster Medicine",
            "Airway Management",
        ],
        "availability": "Immediately",
        "preferred_employment": ["full-time", "locum tenens"],
    },
    {
        "id": "c005",
        "name": "Dr. Emily Park",
        "specialty": "Orthopedic Surgery",
        "years_experience": 7,
        "location": "San Francisco, CA",
        "board_certified": True,
        "licenses": ["CA", "OR", "WA"],
        "education": "Stanford University School of Medicine; Residency at UCSF; Fellowship in Sports Medicine at HSS",
        "skills": [
            "Arthroscopic Surgery",
            "Joint Replacement",
            "Sports Medicine",
            "ACL Reconstruction",
            "Rotator Cuff Repair",
            "Fracture Management",
        ],
        "availability": "90 days",
        "preferred_employment": ["full-time"],
    },
    {
        "id": "c006",
        "name": "Dr. Michael Brown",
        "specialty": "Neurology",
        "years_experience": 15,
        "location": "Philadelphia, PA",
        "board_certified": True,
        "licenses": ["PA", "NJ", "DE"],
        "education": "University of Pennsylvania Perelman School of Medicine; Residency at Penn Medicine; Fellowship in Epilepsy at Cleveland Clinic",
        "skills": [
            "Epilepsy Management",
            "EEG Interpretation",
            "Stroke Neurology",
            "Neuromuscular Disorders",
            "Headache Medicine",
            "Clinical Neurophysiology",
        ],
        "availability": "30 days",
        "preferred_employment": ["full-time"],
    },
    {
        "id": "c007",
        "name": "Dr. Lisa Nguyen",
        "specialty": "Psychiatry",
        "years_experience": 6,
        "location": "Seattle, WA",
        "board_certified": True,
        "licenses": ["WA", "OR"],
        "education": "University of Washington School of Medicine; Residency at UW Medical Center",
        "skills": [
            "Cognitive Behavioral Therapy",
            "Psychopharmacology",
            "Addiction Psychiatry",
            "Telepsychiatry",
            "Forensic Psychiatry",
            "Crisis Intervention",
        ],
        "availability": "Immediately",
        "preferred_employment": ["full-time", "part-time"],
    },
    {
        "id": "c008",
        "name": "Dr. David Kim",
        "specialty": "Radiology",
        "years_experience": 9,
        "location": "Houston, TX",
        "board_certified": True,
        "licenses": ["TX", "LA", "OK"],
        "education": "Baylor College of Medicine; Residency at MD Anderson Cancer Center; Fellowship in Neuroradiology",
        "skills": [
            "MRI Interpretation",
            "CT Scan Analysis",
            "Neuroradiology",
            "Interventional Radiology",
            "PET/CT",
            "Mammography",
        ],
        "availability": "60 days",
        "preferred_employment": ["full-time"],
    },
    {
        "id": "c009",
        "name": "Dr. Amanda Foster",
        "specialty": "Anesthesiology",
        "years_experience": 11,
        "location": "Nashville, TN",
        "board_certified": True,
        "licenses": ["TN", "KY", "AL"],
        "education": "Vanderbilt University School of Medicine; Residency at Vanderbilt University Medical Center",
        "skills": [
            "Regional Anesthesia",
            "Cardiac Anesthesia",
            "Pain Management",
            "Obstetric Anesthesia",
            "Pediatric Anesthesia",
            "Critical Care",
        ],
        "availability": "30 days",
        "preferred_employment": ["full-time", "locum tenens"],
    },
    {
        "id": "c010",
        "name": "Dr. Jennifer Walsh",
        "specialty": "Dermatology",
        "years_experience": 4,
        "location": "Scottsdale, AZ",
        "board_certified": True,
        "licenses": ["AZ", "CA"],
        "education": "Mayo Clinic Alix School of Medicine; Residency at Mayo Clinic Arizona",
        "skills": [
            "Mohs Surgery",
            "Cosmetic Dermatology",
            "Dermatopathology",
            "Skin Cancer Screening",
            "Psoriasis Management",
            "Laser Therapy",
        ],
        "availability": "Immediately",
        "preferred_employment": ["full-time", "part-time"],
    },
    {
        "id": "c011",
        "name": "Dr. Thomas Rivera",
        "specialty": "Gastroenterology",
        "years_experience": 8,
        "location": "Dallas, TX",
        "board_certified": True,
        "licenses": ["TX", "AR"],
        "education": "UT Southwestern Medical School; Residency at Parkland Memorial; Fellowship at UT Southwestern",
        "skills": [
            "Colonoscopy",
            "ERCP",
            "Endoscopic Ultrasound",
            "Inflammatory Bowel Disease",
            "Hepatology",
            "Motility Disorders",
        ],
        "availability": "30 days",
        "preferred_employment": ["full-time"],
    },
    {
        "id": "c012",
        "name": "Dr. Rachel Green",
        "specialty": "Oncology",
        "years_experience": 10,
        "location": "New York, NY",
        "board_certified": True,
        "licenses": ["NY", "NJ", "CT"],
        "education": "Columbia University Vagelos College of Physicians and Surgeons; Residency at NewYork-Presbyterian; Fellowship at Memorial Sloan Kettering",
        "skills": [
            "Medical Oncology",
            "Immunotherapy",
            "Clinical Trials",
            "Breast Cancer",
            "Lung Cancer",
            "Precision Medicine",
        ],
        "availability": "60 days",
        "preferred_employment": ["full-time"],
    },
    {
        "id": "c013",
        "name": "Dr. Anthony Martinez",
        "specialty": "Pulmonology",
        "years_experience": 7,
        "location": "Minneapolis, MN",
        "board_certified": True,
        "licenses": ["MN", "WI", "IA"],
        "education": "University of Minnesota Medical School; Residency at Hennepin County Medical Center; Fellowship at Mayo Clinic",
        "skills": [
            "Bronchoscopy",
            "Pulmonary Function Testing",
            "Critical Care Medicine",
            "COPD Management",
            "Interstitial Lung Disease",
            "Sleep Medicine",
        ],
        "availability": "Immediately",
        "preferred_employment": ["full-time"],
    },
    {
        "id": "c014",
        "name": "Dr. Katherine Lee",
        "specialty": "Obstetrics and Gynecology",
        "years_experience": 9,
        "location": "Portland, OR",
        "board_certified": True,
        "licenses": ["OR", "WA", "CA"],
        "education": "Oregon Health & Science University; Residency at OHSU Hospital",
        "skills": [
            "High-Risk Obstetrics",
            "Minimally Invasive Surgery",
            "Reproductive Endocrinology",
            "Prenatal Ultrasound",
            "Gynecologic Oncology Screening",
            "Family Planning",
        ],
        "availability": "30 days",
        "preferred_employment": ["full-time"],
    },
    {
        "id": "c015",
        "name": "Dr. William Harris",
        "specialty": "Urology",
        "years_experience": 13,
        "location": "Baltimore, MD",
        "board_certified": True,
        "licenses": ["MD", "VA", "DC"],
        "education": "Johns Hopkins University School of Medicine; Residency at Johns Hopkins Hospital; Fellowship in Urologic Oncology",
        "skills": [
            "Robotic Surgery",
            "Prostate Cancer",
            "Kidney Stone Management",
            "Minimally Invasive Surgery",
            "Urologic Oncology",
            "BPH Treatment",
        ],
        "availability": "90 days",
        "preferred_employment": ["full-time"],
    },
    {
        "id": "c016",
        "name": "Dr. Priya Patel",
        "specialty": "Cardiology",
        "years_experience": 3,
        "location": "Atlanta, GA",
        "board_certified": False,
        "licenses": ["GA"],
        "education": "Emory University School of Medicine; Residency at Emory University Hospital; Fellowship in Cardiovascular Medicine (completing)",
        "skills": [
            "Echocardiography",
            "Stress Testing",
            "Cardiac MRI",
            "Heart Failure",
            "Preventive Cardiology",
        ],
        "availability": "90 days",
        "preferred_employment": ["full-time"],
    },
    {
        "id": "c017",
        "name": "Dr. Kevin O'Brien",
        "specialty": "Emergency Medicine",
        "years_experience": 4,
        "location": "Phoenix, AZ",
        "board_certified": True,
        "licenses": ["AZ", "NV"],
        "education": "University of Arizona College of Medicine; Residency at Banner University Medical Center",
        "skills": [
            "Trauma Management",
            "Point-of-Care Ultrasound",
            "Pediatric Emergencies",
            "Cardiac Arrest Management",
            "Procedural Sedation",
        ],
        "availability": "Immediately",
        "preferred_employment": ["full-time", "locum tenens"],
    },
    {
        "id": "c018",
        "name": "Dr. Susan Chang",
        "specialty": "Internal Medicine",
        "years_experience": 20,
        "location": "San Diego, CA",
        "board_certified": True,
        "licenses": ["CA", "AZ"],
        "education": "UCSD School of Medicine; Residency at UC San Diego Medical Center",
        "skills": [
            "Hospital Medicine",
            "Complex Medical Management",
            "Quality Improvement",
            "Medical Education",
            "Palliative Care",
            "Geriatrics",
        ],
        "availability": "60 days",
        "preferred_employment": ["full-time", "part-time"],
    },
    {
        "id": "c019",
        "name": "Dr. Marcus Johnson",
        "specialty": "Neurology",
        "years_experience": 5,
        "location": "Detroit, MI",
        "board_certified": True,
        "licenses": ["MI", "OH"],
        "education": "Wayne State University School of Medicine; Residency at Henry Ford Hospital",
        "skills": [
            "Movement Disorders",
            "Parkinson's Disease",
            "Deep Brain Stimulation",
            "Botulinum Toxin Therapy",
            "Tremor Management",
        ],
        "availability": "30 days",
        "preferred_employment": ["full-time"],
    },
    {
        "id": "c020",
        "name": "Dr. Jessica Taylor",
        "specialty": "Psychiatry",
        "years_experience": 8,
        "location": "Austin, TX",
        "board_certified": True,
        "licenses": ["TX", "NM"],
        "education": "UT Health San Antonio; Residency at Dell Seton Medical Center; Fellowship in Child and Adolescent Psychiatry",
        "skills": [
            "Child Psychiatry",
            "Adolescent Mental Health",
            "ADHD Management",
            "Anxiety Disorders",
            "Family Therapy",
            "Psychopharmacology",
        ],
        "availability": "Immediately",
        "preferred_employment": ["full-time"],
    },
    {
        "id": "c021",
        "name": "Dr. Andrew Patel",
        "specialty": "Orthopedic Surgery",
        "years_experience": 14,
        "location": "Cleveland, OH",
        "board_certified": True,
        "licenses": ["OH", "PA", "MI"],
        "education": "Case Western Reserve University School of Medicine; Residency at Cleveland Clinic; Fellowship in Spine Surgery",
        "skills": [
            "Spine Surgery",
            "Spinal Fusion",
            "Disc Replacement",
            "Minimally Invasive Spine",
            "Scoliosis Correction",
            "Complex Spine Reconstruction",
        ],
        "availability": "60 days",
        "preferred_employment": ["full-time"],
    },
    {
        "id": "c022",
        "name": "Dr. Nicole Adams",
        "specialty": "Dermatology",
        "years_experience": 6,
        "location": "Los Angeles, CA",
        "board_certified": True,
        "licenses": ["CA"],
        "education": "UCLA David Geffen School of Medicine; Residency at UCLA Medical Center",
        "skills": [
            "Cosmetic Dermatology",
            "Injectable Treatments",
            "Acne Management",
            "Melanoma Screening",
            "Eczema Treatment",
            "Phototherapy",
        ],
        "availability": "30 days",
        "preferred_employment": ["full-time", "part-time"],
    },
    {
        "id": "c023",
        "name": "Dr. Daniel Wright",
        "specialty": "Gastroenterology",
        "years_experience": 11,
        "location": "Raleigh, NC",
        "board_certified": True,
        "licenses": ["NC", "SC", "VA"],
        "education": "Duke University School of Medicine; Residency at Duke University Hospital; Fellowship at UNC Chapel Hill",
        "skills": [
            "Advanced Endoscopy",
            "Liver Transplant Evaluation",
            "IBD Management",
            "Celiac Disease",
            "Barrett's Esophagus",
            "Pancreatic Disorders",
        ],
        "availability": "Immediately",
        "preferred_employment": ["full-time"],
    },
    {
        "id": "c024",
        "name": "Dr. Laura Mitchell",
        "specialty": "Oncology",
        "years_experience": 4,
        "location": "Rochester, MN",
        "board_certified": True,
        "licenses": ["MN", "WI"],
        "education": "Mayo Clinic Alix School of Medicine; Residency at Mayo Clinic; Fellowship in Hematology-Oncology at Mayo Clinic",
        "skills": [
            "Hematologic Malignancies",
            "Lymphoma Treatment",
            "Bone Marrow Transplant",
            "CAR-T Cell Therapy",
            "Clinical Research",
        ],
        "availability": "90 days",
        "preferred_employment": ["full-time"],
    },
    {
        "id": "c025",
        "name": "Dr. Christopher Lee",
        "specialty": "Anesthesiology",
        "years_experience": 6,
        "location": "Pittsburgh, PA",
        "board_certified": True,
        "licenses": ["PA", "WV", "OH"],
        "education": "University of Pittsburgh School of Medicine; Residency at UPMC",
        "skills": [
            "Neuroanesthesia",
            "Regional Anesthesia",
            "Ultrasound-Guided Blocks",
            "Trauma Anesthesia",
            "ICU Management",
        ],
        "availability": "30 days",
        "preferred_employment": ["full-time", "locum tenens"],
    },
    {
        "id": "c026",
        "name": "Dr. Megan Scott",
        "specialty": "Pediatrics",
        "years_experience": 15,
        "location": "Columbus, OH",
        "board_certified": True,
        "licenses": ["OH", "IN", "KY"],
        "education": "Ohio State University College of Medicine; Residency at Nationwide Children's Hospital; Fellowship in Pediatric Cardiology",
        "skills": [
            "Pediatric Cardiology",
            "Congenital Heart Disease",
            "Fetal Echocardiography",
            "Pediatric Heart Failure",
            "Cardiac Catheterization",
            "Medical Education",
        ],
        "availability": "60 days",
        "preferred_employment": ["full-time"],
    },
    {
        "id": "c027",
        "name": "Dr. Brian Campbell",
        "specialty": "Pulmonology",
        "years_experience": 9,
        "location": "Tampa, FL",
        "board_certified": True,
        "licenses": ["FL", "GA"],
        "education": "University of South Florida Morsani College of Medicine; Residency at Tampa General; Fellowship at Moffitt Cancer Center",
        "skills": [
            "Interventional Pulmonology",
            "Lung Cancer Screening",
            "EBUS",
            "Pleural Procedures",
            "Asthma Management",
            "Pulmonary Rehabilitation",
        ],
        "availability": "Immediately",
        "preferred_employment": ["full-time"],
    },
    {
        "id": "c028",
        "name": "Dr. Stephanie Ruiz",
        "specialty": "Obstetrics and Gynecology",
        "years_experience": 3,
        "location": "San Antonio, TX",
        "board_certified": False,
        "licenses": ["TX"],
        "education": "UT Health San Antonio Long School of Medicine; Residency at University Hospital (completing)",
        "skills": [
            "Obstetric Care",
            "Prenatal Care",
            "Labor and Delivery",
            "Well-Woman Exams",
            "Contraceptive Counseling",
        ],
        "availability": "90 days",
        "preferred_employment": ["full-time"],
    },
    {
        "id": "c029",
        "name": "Dr. Paul Anderson",
        "specialty": "Radiology",
        "years_experience": 18,
        "location": "St. Louis, MO",
        "board_certified": True,
        "licenses": ["MO", "IL", "KS"],
        "education": "Washington University School of Medicine; Residency at Barnes-Jewish Hospital; Fellowship in Body Imaging",
        "skills": [
            "Body Imaging",
            "Abdominal CT",
            "MRI",
            "Ultrasound",
            "Musculoskeletal Radiology",
            "Radiology Administration",
        ],
        "availability": "30 days",
        "preferred_employment": ["full-time"],
    },
    {
        "id": "c030",
        "name": "Dr. Angela Torres",
        "specialty": "Urology",
        "years_experience": 6,
        "location": "Indianapolis, IN",
        "board_certified": True,
        "licenses": ["IN", "OH", "IL"],
        "education": "Indiana University School of Medicine; Residency at IU Health; Fellowship in Female Pelvic Medicine",
        "skills": [
            "Female Pelvic Medicine",
            "Urinary Incontinence",
            "Pelvic Organ Prolapse",
            "Urodynamics",
            "Minimally Invasive Surgery",
            "Overactive Bladder",
        ],
        "availability": "Immediately",
        "preferred_employment": ["full-time", "part-time"],
    },
]


def seed() -> None:
    """Insert all candidate records into Supabase.

    Skips candidates whose IDs already exist in the table to support
    idempotent re-runs.
    """
    settings = get_settings()
    base_url = f"{settings.supabase_url}/rest/v1/candidates"
    headers = {
        "apikey": settings.supabase_key,
        "Authorization": f"Bearer {settings.supabase_key}",
        "Content-Type": "application/json",
    }

    with httpx.Client(timeout=15.0) as client:
        r = client.get(base_url, headers=headers, params={"select": "id"})
        r.raise_for_status()
        existing_ids = {row["id"] for row in r.json()}

    new_candidates = [c for c in CANDIDATES if c["id"] not in existing_ids]

    if not new_candidates:
        print(f"All {len(CANDIDATES)} candidates already exist. Nothing to insert.")
        return

    batch_size = 10
    inserted = 0
    with httpx.Client(timeout=15.0) as client:
        for i in range(0, len(new_candidates), batch_size):
            batch = new_candidates[i : i + batch_size]
            r = client.post(base_url, headers={**headers, "Prefer": "return=minimal"}, json=batch)
            r.raise_for_status()
            inserted += len(batch)
            print(f"Inserted batch {i // batch_size + 1}: {len(batch)} candidates")

    print(f"\nDone. Inserted {inserted} new candidates (total: {len(CANDIDATES)}).")


if __name__ == "__main__":
    seed()
